# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/felix/Documents/DTU/30082_project_jan_23/Git/DTU/30082/VHDL/Signal_gen_2022/sinusLUT.xci
# IP: The module: 'sinusLUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/felix/Documents/DTU/30082_project_jan_23/Git/DTU/30082/VHDL/Signal_gen_2022/sinusLUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sinusLUT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/felix/Documents/DTU/30082_project_jan_23/Git/DTU/30082/VHDL/Signal_gen_2022/sinusLUT.xci
# IP: The module: 'sinusLUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/felix/Documents/DTU/30082_project_jan_23/Git/DTU/30082/VHDL/Signal_gen_2022/sinusLUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sinusLUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
