@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu Mar 02 21:03:43 +0100 2023
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
=======
REM Generated by Vivado on Thu Mar 02 21:35:28 +0100 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
>>>>>>> a440d7e963381e3b003136e4899446b3c35b2521
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj Black_box_datapath_tb_vlog.prj"
call xvlog  --incr --relax -prj Black_box_datapath_tb_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
REM compile VHDL design sources
echo "xvhdl --incr --relax -prj Black_box_datapath_tb_vhdl.prj"
call xvhdl  --incr --relax -prj Black_box_datapath_tb_vhdl.prj -log xvhdl.log
call type xvhdl.log >> compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
