@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 02 16:46:34 +0100 2023
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Black_box_datapath_tb_behav -key {Behavioral:sim_1:Functional:Black_box_datapath_tb} -tclbatch Black_box_datapath_tb.tcl -view C:/Users/felix/Documents/DTU/62711_Digital_systems_design/Git/DTU/62711/VHDLV3/VHDL/VHDL_Gruppe4/Datapath/Black_box_datapath_tb_behav.wcfg -log simulate.log"
call xsim  Black_box_datapath_tb_behav -key {Behavioral:sim_1:Functional:Black_box_datapath_tb} -tclbatch Black_box_datapath_tb.tcl -view C:/Users/felix/Documents/DTU/62711_Digital_systems_design/Git/DTU/62711/VHDLV3/VHDL/VHDL_Gruppe4/Datapath/Black_box_datapath_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
