webtalk_init -webtalk_dir C:/Users/felix/Documents/DTU/62711_Digital_systems_design/Git/DTU/62711/VHDLV3/VHDL/VHDL_Gruppe4/Datapath/project_2.sim/sim_1/behav/xsim/xsim.dir/Black_box_datapath_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar  2 21:42:09 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e14f39c1-b56a-41b3-9f65-0438f3ab15b1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d13b35b9ea6f40b3bb5ca034a9d85326" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7124_KB" -context "xsim\\usage"
webtalk_transmit -clientid 551902072 -regid "" -xml C:/Users/felix/Documents/DTU/62711_Digital_systems_design/Git/DTU/62711/VHDLV3/VHDL/VHDL_Gruppe4/Datapath/project_2.sim/sim_1/behav/xsim/xsim.dir/Black_box_datapath_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/felix/Documents/DTU/62711_Digital_systems_design/Git/DTU/62711/VHDLV3/VHDL/VHDL_Gruppe4/Datapath/project_2.sim/sim_1/behav/xsim/xsim.dir/Black_box_datapath_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/felix/Documents/DTU/62711_Digital_systems_design/Git/DTU/62711/VHDLV3/VHDL/VHDL_Gruppe4/Datapath/project_2.sim/sim_1/behav/xsim/xsim.dir/Black_box_datapath_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
